---
abstract: 'Apache Clownfish Runtime'
author:
  - 'The Apache Lucy Project <dev at lucy dot apache dot org>'
build_requires:
  Clownfish::CFC: 0.004001
  Devel::PPPort: 3.14
  ExtUtils::CBuilder: 0.21
  ExtUtils::ParseXS: 2.18
  Module::Build: 0.280801
configure_requires:
  Clownfish::CFC::Perl::Build: 0.004001
  Module::Build: 0.280801
dynamic_config: 1
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120921'
keywords:
  - clownfish
license: apache
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Clownfish
provides:
  Clownfish:
    file: lib/Clownfish.pm
    version: 0.004001
  Clownfish::ByteBuf:
    file: lib/Clownfish/ByteBuf.pm
    version: 0.004001
  Clownfish::Class:
    file: lib/Clownfish/Class.pm
    version: 0.004001
  Clownfish::Err:
    file: lib/Clownfish/Err.pm
    version: 0.004001
  Clownfish::Hash:
    file: lib/Clownfish/Hash.pm
    version: 0.004001
  Clownfish::LockFreeRegistry:
    file: lib/Clownfish/LockFreeRegistry.pm
    version: 0.004001
  Clownfish::Method:
    file: lib/Clownfish.pm
    version: 0.004001
  Clownfish::Num:
    file: lib/Clownfish/Num.pm
    version: 0.004001
  Clownfish::Obj:
    file: lib/Clownfish/Obj.pm
    version: 0.004001
  Clownfish::StackString:
    file: lib/Clownfish.pm
    version: 0.004001
  Clownfish::String:
    file: lib/Clownfish/CharBuf.pm
    version: 0.004001
  Clownfish::Test:
    file: lib/Clownfish/Test.pm
    version: 0.004001
  Clownfish::Util::StringHelper:
    file: lib/Clownfish/Util/StringHelper.pm
    version: 0.004001
  Clownfish::VArray:
    file: lib/Clownfish/VArray.pm
    version: 0.004001
  Clownfish::ViewByteBuf:
    file: lib/Clownfish.pm
    version: 0.004001
requires:
  perl: v5.8.3
resources:
  bugtracker: https://issues.apache.org/jira/browse/CLOWNFISH
  homepage: http://lucy.apache.org
  repository: https://git-wip-us.apache.org/repos/asf/lucy-clownfish.git
version: v0.4.1
